// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBjhKdxw6eZDxuXPEoBEC0N7gp0yiQMxI',
    appId: '1:551719927047:web:eb2abca0c71633c61c99a2',
    messagingSenderId: '551719927047',
    projectId: 'whatsapp-mesenger-26788',
    authDomain: 'whatsapp-mesenger-26788.firebaseapp.com',
    storageBucket: 'whatsapp-mesenger-26788.appspot.com',
    measurementId: 'G-E188SLZSN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC76I6Z7z3AgTsfiSP9z2l3RH9OsQKvmKk',
    appId: '1:551719927047:android:0512849c449cad371c99a2',
    messagingSenderId: '551719927047',
    projectId: 'whatsapp-mesenger-26788',
    storageBucket: 'whatsapp-mesenger-26788.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNoa5veHzWWBJGvO0ZhUMbs3R80_TGIQg',
    appId: '1:551719927047:ios:ac75692966549df31c99a2',
    messagingSenderId: '551719927047',
    projectId: 'whatsapp-mesenger-26788',
    storageBucket: 'whatsapp-mesenger-26788.appspot.com',
    iosBundleId: 'com.example.whatsappMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNoa5veHzWWBJGvO0ZhUMbs3R80_TGIQg',
    appId: '1:551719927047:ios:c7fd41a8437842451c99a2',
    messagingSenderId: '551719927047',
    projectId: 'whatsapp-mesenger-26788',
    storageBucket: 'whatsapp-mesenger-26788.appspot.com',
    iosBundleId: 'com.example.whatsappMessenger.RunnerTests',
  );
}
